### PR TITLE
TraceableRouteLoader: fix type error 

### PR DESCRIPTION
**Pull request by Kaspiman**
Error when `bin/console c:c:`

```
In TraceableRouteLoader.php line 69:
                                                                                               
  Attempted to call an undefined method named "getDeclaringClass" of class "ReflectionClass". 
```

### CODE REVIEW

**Comment by Kaspiman** [comment]
[gaelreyrol](https://github.com/gaelreyrol)

**Comment by Kaspiman** [comment]
@gaelreyrol Hello! Please, review.

**Comment by gaelreyrol** [comment]
Hi @Kaspiman,

Thanks for reporting this, I will review this as soon as I have time to do so, in the mean time can you please solve CI errors?

**Comment by Kaspiman** [comment]
@gaelreyrol Sure!

**Comment by Kaspiman** [comment]
@gaelreyrol Hello, how to fix Fossa Scan check? https://github.com/FriendsOfOpenTelemetry/opentelemetry-bundle/actions/runs/11796593160/job/32860468020?pr=91

`Error: Input required and not supplied: api-key`

**Comment by gaelreyrol** [comment]
> @gaelreyrol Hello, how to fix Fossa Scan check? https://github.com/FriendsOfOpenTelemetry/opentelemetry-bundle/actions/runs/11796593160/job/32860468020?pr=91
> 
> `Error: Input required and not supplied: api-key`

Hi @Kaspiman, don't bother with the "Fossa Scan Check & Test", it's because the workflow is ran from a fork, I need to disable it in those case.

**Comment by Kaspiman** [comment]
So, my code is ready to merge! Also i created https://github.com/FriendsOfOpenTelemetry/opentelemetry-bundle/pull/92

**Comment by gaelreyrol** [comment]
Hi @Kaspiman, could you explain how did you encountered this error? I am trying to setup a reproducer so I can cover it with a test case.

**Comment by gaelreyrol** [comment]
> Hi @Kaspiman, could you explain how did you encountered this error? I am trying to setup a reproducer so I can cover it with a test case.

I've managed to reproduce the error you reported, I updated your PR to simplify the fix and keep the structure I used. 
Thanks again for your work!

**Review by gaelreyrol — APPROVED** [review]

**Review by gaelreyrol — APPROVED** [review]

**Pull request merged**
